# Generated by Django 3.1.5 on 2021-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS_QuA', '0002_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_data',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
