# Generated by Django 3.2.9 on 2021-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS_Back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
