# Generated by Django 3.1.5 on 2022-01-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS_Back', '0003_alter_notes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='subject_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
